name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run chart-releaser (GitHub Pages)
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      
      - name: Publish Helm charts to GHCR
        run: |
          # Find all chart directories
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "Processing chart: $chart"
              chart_name=$(basename "$chart")
              chart_version=$(grep 'version:' "$chart/Chart.yaml" | awk '{print $2}')
              
              # Package the chart
              helm package "$chart"
              
              # Push to GHCR
              helm push "${chart_name}-${chart_version}.tgz" oci://ghcr.io/${{ github.repository_owner }}/charts
              
              echo "Published $chart_name v$chart_version to GHCR"
            fi
          done
